services:
  - name: ctrader-webhook
    type: web
    env: python
    buildCommand: ""
    startCommand: python webhook_listener.py
    envVars:
      - key: HOST_TYPE
        value: "demo" 
      - key: APP_CLIENT_ID
        value: ""
      - key: APP_CLIENT_SECRET
        value: ""
      - key: ACCESS_TOKEN
        value: ""
      - key: ACCOUNT_ID
        value: ""
      - key: WEBHOOK_USER
        value: ""
      - key: WEBHOOK_PASS
        value: ""
