services:
  - type: web
    name: tradingview-ctrader-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: CTRADER_HOST
        sync: false
      - key: CTRADER_PORT
        sync: false
      - key: APP_CLIENT_ID
        sync: false
      - key: APP_CLIENT_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: ACCOUNT_ID
        sync: false